Repository wecode-bootcamp-korea/29-1st-Dr-Mataeng-frontend, pull requests merged in 2022-02, with the labels that each got.

#4 [29기 장예지] add 회원가입 유효성 검사 기능
  src/components/Filter/Filter.js
  src/components/Filter/Filter.scss
  src/pages/SignUp/InputList.js
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
  src/pages/SignUp/SignUpInput.js
Labels: Status: 리뷰 요청

#18 [29기 오수민] 이미지 슬라이드 컴포넌트 추가
  src/pages/Main/ImageSlide.js
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청, Status: 도움 요청

#15 [29기 오수민] 로그인페이지 인증인가
  src/pages/Login/Login.scss
  src/pages/Login/login.js
Labels: Status: Accepted

#24 [29기 유재민] 전체 페이지 폰트 스타일 수정
  public/index.html
  src/styles/common.scss
  src/styles/reset.scss
Labels: Status: 리뷰 요청

#17 [29기 유재민] 검색 페이지 추가 기능 구현 중
  public/data/search.json
  public/images/search/icon-down-chevron.png
  public/images/search/icon-filter.png
  public/images/search/icon-heart.png
  public/images/search/icon-left-arrow.png
  public/images/search/product.png
  src/components/header/header.js
  src/pages/Search/Search.js
  src/pages/Search/Search.scss
Labels: Status: 리뷰 요청

#20 [29기 유재민] 상세페이지 데이터 연동 및 추가 기능 구현 중
  public/data/productDetailData.json
  public/images/productDetail/icon-love.png
  public/images/productDetail/icon-minus.png
  public/images/productDetail/icon-plus.png
  public/images/productDetail/icon-share.png
  public/images/productDetail/productDetail.jpeg
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/ProductStock.js
Labels: Status: 리뷰 요청

#22 [29기 유재민] 헤더 추가 기능 구현 중
  src/Router.js
  src/components/header/header.js
Labels: Status: 리뷰 요청

#25 [29기 장예지] Product List 페이지 구현
  public/data/productList.json
  public/images/productList/icon-down-chevron.png
  public/images/productList/icon-filter.png
  public/images/productList/icon-heart.png
  public/images/productList/icon-left-arrow.png
  public/images/productList/product.png
  src/Router.js
  src/pages/ProductList/Filter.js
  src/pages/ProductList/Filter.scss
  src/pages/ProductList/Pagination.js
  src/pages/ProductList/Pagination.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/SignUp/SignUp.scss
Labels: Status: 리뷰 요청

#23 [29기 오수민]장바구니페이지 레이아웃
  public/images/icon/cancel.png
  public/images/icon/shopping-cart.png
  public/images/icon/trash-can.png
  src/pages/WishList/Empty.js
  src/pages/WishList/OrderPrice.js
  src/pages/WishList/ProductList.js
  src/pages/WishList/WishList.js
  src/pages/WishList/WishList.scss
  src/pages/WishList/wishlistData.json
Labels: Status: 리뷰 요청

#29 [29기 유재민] 결제 페이지 마크업
  public/images/payment/icon-bag.png
  public/images/payment/icon-down-arrow-white.png
  public/images/payment/icon-left-arrow.png
  public/images/payment/icon-up-arrow-white.png
  public/images/payment/icon-user.png
  public/images/payment/tum-test.jpeg
  src/pages/Payment/Payment.js
  src/pages/Payment/Payment.scss
Labels: Status: 리뷰 요청

#30 [29기 유재민] 마이페이지 주문 내역 마크업
  public/images/mypage/icon-bag.png
  public/images/mypage/icon-down-arrow-white.png
  public/images/mypage/icon-up-arrow-white.png
  public/images/mypage/tum-test.jpeg
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyPage.scss
Labels: Status: 리뷰 요청

#33 [29기 장예지] top 버튼 기능
  public/images/topBt/up-arrow.png
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/TopBt.js
  src/pages/SignUp/TopBt.scss
Labels: Status: 리뷰 요청

#34 [29기 장예지] header 부분 수정
  public/images/header/header-logo.png
  public/images/header/header-logo.svg
  src/Router.js
  src/components/header/header.js
  src/components/header/header.scss
Labels: Status: 리뷰 요청

#26 [29기 유재민] 상세 페이지 데이터 연동 구현 중
  src/pages/ProductDetail/ProductDetail.js
Labels: Status: 리뷰 요청

#35 [29기 유재민] reset css a tag style 변경
  src/styles/reset.scss
Labels: Status: 리뷰 요청

#36 [29기 오수민] login -> SignIn
  src/Router.js
  src/pages/SignIn/SignIn.js
  src/pages/SignIn/SignIn.scss
Labels: Status: 리뷰 요청

#38 [29기 오수민] 장바구니페이지
  src/pages/WishList/ProductList.js
  src/pages/WishList/WishList.js
  src/pages/WishList/WishList.scss
Labels: Status: 리뷰 요청

#39 [29기 장예지] header 로그아웃 기능 추가
  src/components/header/header.js
  src/components/header/header.scss
Labels: Status: Accepted

#40 [29기 장예지] top 버튼 구성
  src/pages/Main/Main.js
  src/pages/ProductList/Pagination.scss
  src/pages/ProductList/ProductList.js
Labels: Status: 리뷰 요청

#41 [29기 오수민] 로그인페이지
  src/pages/SignIn/SignIn.js
  src/pages/SignIn/SignIn.scss
Labels: Status: 리뷰 요청

#42 [29기 오수민] 장바구니페이지
  src/pages/WishList/WishList.js
Labels: Status: 리뷰 요청

#45 [29기 장예지] main 페이지 오류 수정
  src/pages/Main/ImageScroll.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
Labels: Status: 리뷰 요청

#46 [29기 장예지] header 상수데이터 수정
  src/components/header/header.js
Labels: Status: 리뷰 요청

#47 [29기 장예지] 필터 기능 수정
  src/pages/ProductList/Filter.js
  src/pages/ProductList/ProductList.js
Labels: Status: 리뷰 요청

#48 [29기 오수민] api url 관리
  src/config.js
Labels: Status: 리뷰 요청

#50 [29기 오수민]로그인페이지 아이디 자동저장기능
  src/pages/SignIn/SignIn.js
Labels: Status: 리뷰 요청

#49 [29기 유재민] 네비게이션 하위메뉴 클릭 시 네비게이션 창 닫힘 기능 추가
  src/components/header/Nav.js
  src/components/header/NavMenu.js
  src/components/header/header.js
Labels: Status: 리뷰 요청

#51 [29기 유재민] 결제 페이지 데이터 연동 구현 완료
  src/pages/Payment/Payment.js
  src/pages/Payment/Payment.scss
Labels: Status: 리뷰 요청

#52 [29기 장예지] pagination button to top
  src/pages/ProductList/ProductList.js
Labels: Status: 리뷰 요청

#53 [29기 유재민] 마이페이지 결제내역 조건부렌더링 기능 추가
  src/pages/MyPage/MyPage.js
Labels: Status: 리뷰 요청

#54 [29기 유재민] 검색 기능 구현 완료
  src/components/header/header.js
  src/components/header/header.scss
  src/pages/Search/Search.js
  src/pages/Search/Search.scss
Labels: Status: 리뷰 요청

#55 [29기 장예지] add:email default
  src/pages/SignUp/SignUp.js
Labels: Status: 리뷰 요청

#56 [29기 유재민] 검색 페이지 결과 없는 경우 처리 완료
  public/images/search/search_none.png
  src/pages/Search/Search.js
  src/pages/Search/Search.scss
Labels: Status: 리뷰 요청

#58 [29기 유재민] 검색 입력 값 0인 경우 페이지 이동 막기 수정 완료
  src/components/header/header.js
Labels: Status: 리뷰 요청

#57 [29기 오수민] api 주소 추가
  src/config.js
  src/pages/MyPage/MyPage.js
  src/pages/Payment/Payment.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductList/ProductList.js
  src/pages/Search/Search.js
  src/pages/SignIn/SignIn.js
  src/pages/SignUp/SignUp.js
  src/pages/WishList/ProductList.js
  src/pages/WishList/WishList.js
Labels: Status: 리뷰 요청
